-- USER SQL
CREATE USER APEX_DEMO IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER APEX_DEMO QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO APEX_DEMO ;
ALTER USER APEX_DEMO DEFAULT ROLE "CONNECT";

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO APEX_DEMO ;
GRANT CREATE TRIGGER TO APEX_DEMO ;
GRANT CREATE MATERIALIZED VIEW TO APEX_DEMO ;
GRANT CREATE VIEW TO APEX_DEMO ;
GRANT CREATE SESSION TO APEX_DEMO ;
GRANT CREATE EXTERNAL JOB TO APEX_DEMO ;
GRANT CREATE TABLE TO APEX_DEMO ;
GRANT CREATE TYPE TO APEX_DEMO ;
GRANT CREATE SYNONYM TO APEX_DEMO ;
GRANT CREATE SEQUENCE TO APEX_DEMO ;
GRANT CREATE DATABASE LINK TO APEX_DEMO ;
GRANT CREATE PROCEDURE TO APEX_DEMO ;
GRANT apex_administrator_role to APEX_DEMO;
grant execute on dbms_application_info to APEX_DEMO;

